#!/bin/bash

install() {
  # get system os/arch
  local arch="$PACKAGE_OS_ARCH"
  local kernel="$PACKAGE_OS_KERNEL"
  local platform="$PACKAGE_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
  local tmp_dir="$PACKAGE_TMP_DIR"

  # reference: https://developer.hashicorp.com/vagrant/downloads
  if [ "$(os::is_macos)" = "true" ]; then
    pm install vagrant
  elif [ "$(os::is_ubuntu)" = "true" ]; then
    wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    pm update && pm install vagrant
  elif [ "$(os::is_centos)" = "true" ]; then
    pm install -y yum-utils
    sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    pm install -y vagrant
  elif [ "$(os::is_fedora)" = "true" ]; then
    pm install -y dnf-plugins-core
    pm config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    pm install -y vagrant
  else
    log::error "unsupported operating system"
    return 1
  fi
}

export -f install
